### PR TITLE
Feat/add ios swiftui

### LINKED ISSUE #3: iOS Coming Soon
# Bug report

## Describe the bug
README file indicates iOS is coming soon.  Last commit was 7 months ago.

Wondering if there is a pre-release version in the works?

Or maybe the plan to add iOS changed because there was something already available?  Maybe I am looking in the wrong place?

Thank you in advance!
Del

### PR DESCRIPTION
**Pull request by thorsten-stripe**
Closes #3 

- Simple Firebase Auth email login
- Stripe payment sheet integration https://stripe.com/docs/mobile/payments-ui-beta

### CODE REVIEW

**Comment by davidme-stripe** [comment]
Neat! I'm not super familiar with Firebase, but this looks great!

* You might want to add `xcuserdata` to the .gitignore so that you don't commit your username's config files.
* Also, weird nit, but it looks like everything is indented with 8 spaces on GitHub.

**Review by davidme-stripe — APPROVED** [review]

**Comment by thorsten-stripe** [comment]
Thanks @davidme-stripe. I've been struggling with formatting in Xcode, it always seems to be wonky. Would appreciate any tips you might have.

**Comment by davidme-stripe** [comment]
Might be in the Text Editing -> Indentation settings panel?
image

**Comment by thorsten-stripe** [comment]
Hm, yah, that works fine as long as I type from scratch. As soon as I copy paste stuff from docs it gets all messed up. Really miss my "format on save" functionality from vscode here.

**Comment by davidme-stripe** [comment]
Try selecting the code and hitting `ctrl i`, that should re-indent it.

**Comment by thorsten-stripe** [comment]
Man, I didn't think I had to select the code for that to work 🙈 Thanks for this!

**Pull request merged**
